[package]
authors = ["zCloak"]
description = "wasm crypto libraries."
edition = "2021"
license = "Apache-2.0"
name = "wasm"
publish = false
repository = "https://github.com/zCloak-Network/zkid-sdk/"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
blake2-rfc = "0.2.18"
ed25519-dalek = { version = "1.0.0-pre.4", features = [] }
hmac = "0.7.0"
secp256k1 = { version = "0.21.2", default-features = false, features = ["recovery", "global-context"] }
pbkdf2 = { version = "0.3.0", default-features = false }
scrypt = { version = "0.2", default-features = false }
sha2 = "0.8.1"
tiny-bip39 = { version = "0.7", default-features = false }
tiny-keccak = { version = "2.0.1", features = ["keccak"] }
rescue = {git = "https://github.com/zCloak-Network/rescue-hash", branch = "main", default-features = false}
wasm-bindgen = "=0.2.83"

[dev-dependencies]
criterion = "0.3.3"
num-bigint = "0.3.0"

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = "z"
panic = "abort"
rpath = false

