[package]
authors = ["zCloak"]
description = "rescue crypto libraries."
edition = "2021"
license = "Apache-2.0"
name = "rescue"
publish = false
repository = "https://github.com/zCloak-Network/zkid-sdk/"
version = "0.0.0"

[lib]
bench = false

[dependencies]
serde_json = "1.0.0"
hex = "0.4.2"
sp-std = { git = "https://github.com/zCloak-Network/substrate", default-features = false }
math = {verision = "0.4", path = "src/utils/winterfell-math", package="winter-math",default-features = false}
crypto = {verision = "0.4", path = "src/utils/winterfell-crypto", package="winter-crypto",default-features = false}
utils-core = {version = "0.4", path = "src/utils/winterfell-utils/utils/core", package = "winter-utils", default-features = false}

[dev-dependencies]
criterion = "0.3.3"
num-bigint = "0.3.0"
[features]
default = ["std"]
std = [
    "sp-std/std",
]

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = "z"
panic = "abort"
rpath = false

